<a href="https://colab.research.google.com/github/ndb796/AI-Theory-and-Practical-Project/blob/master/PyTorch%EC%9D%98%20Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor의 **초기화**

In [6]:
from __future__ import print_function
import torch

# 리스트를 Tensor로 변환합니다.
a = torch.tensor([1, 2, 3])
print(a)

# 초기화되지 않은 행렬을 생성합니다.
a = torch.empty(4, 5)
print(a)

# 랜덤 값으로 초기화된 행렬을 생성합니다.
a = torch.rand(4, 5)
print(a)

# 0으로 초기화된 행렬을 생성합니다.
a = torch.zeros(5, 3, dtype=torch.long)
print(a)

tensor([1, 2, 3])
tensor([[1.8695e-36, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0.3077, 0.0372, 0.6517, 0.3955, 0.6162],
        [0.3296, 0.7419, 0.7814, 0.8540, 0.0581],
        [0.8697, 0.6507, 0.2191, 0.1365, 0.5866],
        [0.6668, 0.2653, 0.0097, 0.3237, 0.9265]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Tensor의 **더하기**

In [4]:
from __future__ import print_function
import torch

# Tensor의 크기를 구합니다.
a = torch.tensor([1, 1])
print(a.size())

# Tensor 더하기
b = torch.tensor([2, 3])
c = a + b

print(c)

torch.Size([2])
tensor([3, 4])


Tensor의 **곱하기**

* 기본적인 Tensor의 곱셈은 동일한 위치의 원소를 곱합니다.

In [7]:
from __future__ import print_function
import torch

# Tensor 곱하기
a = torch.tensor([[0, 1], [2, 3]])
b = torch.tensor([[1, 2], [3, 4]])
c = a * b

print(c)

tensor([[ 0,  2],
        [ 6, 12]])


Tensor의 **행렬 곱**

* Tensor는 행렬 곱 연산을 지원합니다.

In [0]:
from __future__ import print_function
import torch

# Tensor 곱하기
a = torch.tensor([[0, 1], [2, 3]])
b = torch.tensor([[1, 2], [3, 4]])
c = torch.matmul(a, b)

print(c)

서로 다른 형태의 Tensor 연산하기

* 브로드캐스트: 형태가 다른 행렬을 연산할 수 있도록 행렬의 형태를 동적으로 변환

In [9]:
from __future__ import print_function
import torch

# Tensor의 크기를 구합니다.
# Tensor 브로드캐스트
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1, 2, 3], [1, 2, 3]])
c = a + b
print(c)

tensor([[2, 4, 6],
        [2, 4, 6]])


Tensor **형태 변경**

* Tensor는 인덱싱 표기법을 사용할 수 있습니다.
* 다양한 방법으로 형태를 변경할 수 있습니다.

In [14]:
from __future__ import print_function
import torch

a = torch.tensor([
  [0, 1, 2, 3],
  [4, 5, 6, 7],
  [0, 1, 2, 3],
  [4, 5, 6, 7]
])

print(a[:, 2])
a = a.view(16)
print(a)
a = a.view(4, 4)
print(a)
a = a.view(-1, 8)
print(a)

tensor([2, 6, 2, 6])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7],
        [0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7]])


Tensor와 Numpy 변환

In [16]:
from __future__ import print_function
import torch
import numpy as np

a = torch.tensor([
  [0, 1, 2, 3],
  [4, 5, 6, 7]
])
print(a)

b = a.numpy()
print(b)

c = torch.from_numpy(b)
print(c)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
[[0 1 2 3]
 [4 5 6 7]]
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
